give all
virtualCrypto-discord/virtualCrypto2 pull request #246
Opened 2021-04-06 15:09 UTC by tignear

2021-04-06 23:41 UTC, sizumita requested changes
あと、今から新しいコマンドを追加しようとすると古いやつに加えて同じ名前のやつがも一つできるみたいなのよ....どうすればいいんだっけ

2021-04-06 23:41 UTC, sizumita commented on priv/register-commands.exs
> +      "description" => "発行枠から通過を発行します。管理者権限が必要です。amountを省略した場合は全額が指定されたuserに発行されます。",
たいぽ

2021-04-07 08:20 UTC, tignear commented
> あと、今から新しいコマンドを追加しようとすると古いやつに加えて同じ名前のやつがも一つできるみたいなのよ....どうすればいいんだっけ

deleteして追加すればいいのでは(私はそれは別のPRでやるつもりというかこのコマンドも当分維持するつもり(経過措置は必要なので))

2021-04-10 03:35 UTC, sizumita approved these changes

2021-04-10 05:56 UTC, merged