fix behavior at info command error
virtualCrypto-discord/virtualCrypto2 pull request #65
Opened 2021-01-12 11:46 UTC by tignear

2021-01-12 14:46 UTC, sizumita requested changes

2021-01-12 14:46 UTC, sizumita commented on lib/virtualCrypto_web/views/interactions_view/info.ex
> +    "エラー: 通貨が見つかりませんでした。"
optionsを引数で渡していたのはこのエラー表示を変えるためだったので（引数が全くないかどうか知りたかった）、optionsを渡すのを消していいと思います。

2021-01-12 14:46 UTC, sizumita commented on lib/virtualCrypto_web/command_handler.ex
> +        {:error, nil, nil, nil, options}
ここ

2021-01-12 14:48 UTC, tignear commented on lib/virtualCrypto_web/command_handler.ex
> +        {:error, nil, nil, nil, options}
もう少し正確な条件にしたほうがいいのかな
(Mapのパターンマッチングはelixirにおいて完全一致ではない)

2021-01-12 14:50 UTC, sizumita commented on lib/virtualCrypto_web/command_handler.ex
> +        {:error, nil, nil, nil, options}
どうだろう、治ったならそれでいい気がする（）

2021-01-12 14:51 UTC, tignear commented on lib/virtualCrypto_web/command_handler.ex
> +        {:error, nil, nil, nil, options}
UIで妥協したので治ったと言えるんだろうか()

2021-01-12 14:53 UTC, sizumita commented on lib/virtualCrypto_web/command_handler.ex
> +        {:error, nil, nil, nil, options}
許されて欲しいw
正確な条件にしてもいいと思うけど多分めんどくさいので...

2021-01-12 14:55 UTC, tignear commented on lib/virtualCrypto_web/command_handler.ex
> +        {:error, nil, nil, nil, options}
options廃止了解(

2021-01-15 01:26 UTC, sizumita approved these changes

2021-01-15 01:40 UTC, merged