請求関連
virtualCrypto-discord/virtualCrypto2 pull request #71
Opened 2021-01-13 04:07 UTC by sizumita

close #33

2021-01-13 04:07 UTC, sizumita commented
draft作ろうとしたら間違っちゃったw

2021-01-14 10:17 UTC, tignear requested changes
はい

2021-01-14 10:17 UTC, tignear commented on lib/virtualCrypto_web/command_handler.ex
> +    int_user_id = user["id"]
ん

2021-01-14 10:17 UTC, tignear commented on lib/virtualCrypto_web/command_handler.ex
> +    int_user_id = user["id"]
型に

2021-01-14 10:17 UTC, tignear commented on lib/virtualCrypto_web/command_handler.ex
> +    int_user_id = user["id"]
名前が

2021-01-14 10:38 UTC, tignear commented
https://github.com/virtualCrypto-discord/virtualCrypto2/pull/71#discussion_r557285715
?

2021-01-14 13:02 UTC, sizumita commented
fixed

2021-01-14 13:22 UTC, tignear requested changes

2021-01-14 13:22 UTC, tignear commented on lib/virtualCrypto/money/service.ex
> +    %Money.Claim{
エラー処理の不足

2021-01-14 13:29 UTC, sizumita commented on lib/virtualCrypto/money/service.ex
> +    %Money.Claim{
本当だ...

2021-01-14 13:30 UTC, tignear requested changes

2021-01-14 13:30 UTC, tignear commented on lib/virtualCrypto_web/command_handler.ex
> +    {:ok, claim} = VirtualCrypto.Money.create_claim(int_user_id, int_payer_id, options["sub_options"]["unit"], options["sub_options"]["amount"], (if options["sub_options"]["message"], do: options["su
空文字列入れるくらいならNULL入れたほうがよくない?

2021-01-14 15:06 UTC, tignear approved these changes

2021-01-14 15:07 UTC, tignear commented
あとはすみどらさんが確認して問題あれば言ってくださいー

2021-01-14 23:28 UTC, sizumita commented
良さげです

2021-01-14 23:28 UTC, merged