release 0.0.1
virtualCrypto-discord/virtualCrypto2 pull request #82
Opened 2021-01-15 11:33 UTC by sizumita

2021-01-15 12:22 UTC, tignear submitted a review, later dismissed
よさげ(適当)

2021-01-15 16:43 UTC, tignear requested changes
これはひどい(私は何を見ていたのだろう)

2021-01-15 16:43 UTC, tignear commented on assets/elm/src/Mypage.elm
> +    { url = "http://localhost/api/v1/user/@me"
Crazy!

2021-01-15 16:43 UTC, tignear commented on assets/elm/src/Mypage.elm
> +    { url = "http://localhost/api/v1/balance/@me"
()

2021-01-15 22:17 UTC, sizumita commented on assets/elm/src/Mypage.elm
> +    { url = "http://localhost/api/v1/user/@me"
これはひどいwwwww

2021-01-18 06:54 UTC, sizumita commented
とりあえず閉じるわw

2021-01-18 06:54 UTC, closed without merging